### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by lantis1008** [lantis1008/gargoyle-plugin-spectrum-analyser#1]
- [x] Add legend and rollover effects
- [x] Add 40MHz support for 2.4GHz
- [x] Add 5GHz support
- [x] Add 40/80MHz support for 5GHz
